version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.6.4
    environment:
      PIPENV_VENV_IN_PROJECT: true
      PYTHONPATH: "/home/circleci/project"

jobs:
  python-prepare:
    executor: python
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-prepare-v1-{{ .Branch }}-{{ checksum "requirements/base.txt" }}
      - run:
          name: Installing dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements/base.txt
            pip install -r requirements/tests.txt
      - save_cache:
          paths:
            - .venv
          key: python-prepare-v1-{{ .Branch }}-{{ checksum "requirements/base.txt" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  python-lint:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Flake8 check
          command: |
            . .venv/bin/activate
            flake8 --show-source --format junit-xml --output-file flake8.xml lintlens
      - store_test_results:
          path: flake8.xml
      - store_artifacts:
          path: flake8.xml

  python-test:
    executor: python
    steps:
      - attach_workspace:
          at: .
      - run:
          name: pytest
          command: |
            . .venv/bin/activate
            pytest --junitxml=pytest.xml --cov-report html --cov=lintlens --cov-config=./.coveragerc .
      - store_test_results:
          path: pytest.xml
      - store_artifacts:
          path: pytest.xml
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - python-prepare
      - python-lint:
          requires:
            - python-prepare
      - python-test:
          requires:
            - python-prepare
